version: "3.7"

volumes:
  frontend-public-volume:
  socket-volume:

services:
  mongo:
    image: mongo:2.6.4
    ports:
      - target: 27017
        published: 27017

  nginx:
    image: jnorwood/stupidchess-nginx:19.1205
    volumes:
      - type: volume
        source: socket-volume
        target: /opt/stupidchess/sockets
    ports:
      - target: 23080
        published: 80

  uwsgi:
    image: jnorwood/stupidchess-uwsgi:current
    build: .
    entrypoint:
      - uwsgi
      - --ini
      - /opt/stupidchess/uwsgi.ini:local
    environment:
      JCONFIGURE_ACTIVE_PROFILES: LCL
      JCONFIGURE_CONFIG_DIRECTORIES: /opt/stupidchess/config
    volumes:
      - type: volume
        source: socket-volume
        target: /opt/stupidchess/sockets
      - type: bind
        source: ./etc/uwsgi/uwsgi.ini
        target: /opt/stupidchess/uwsgi.ini
        read_only: true
      - type: bind
        source: ./config
        target: /opt/stupidchess/config
        read_only: true
