version: "3"

volumes:
  socket-volume:
  frontend-public-volume:

services:
  mongo:
    image: mongo:2.6.4
    ports:
      - 27017:27017

  nginx:
    image: jnorwood/stupidchess-nginx:19.1109.0
    volumes:
      - socket-volume:/var/run
    ports:
      - 80:80

  uwsgi:
    image: jnorwood/stupidchess-uwsgi:current
    build: .
    entrypoint:
      - uwsgi
      - --ini
      - /etc/uwsgi/uwsgi.ini:local
    environment:
      - JCONFIGURE_ACTIVE_PROFILES=LCL
      - JCONFIGURE_CONFIG_DIRECTORIES=/var/lib/johnmalcolmnorwood/stupidchess/server/config
    volumes:
      - ./config:/var/lib/johnmalcolmnorwood/stupidchess/server/config:ro
      - ./etc/uwsgi:/etc/uwsgi:ro
      - socket-volume:/var/run
