version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

handlers:
  default:
    class: logging.StreamHandler
    formatter: default

root:
  level: INFO
  handlers: [default]

loggers:
  com.johnmalcolmnorwood.auth:
    level: DEBUG
    handlers: [default]
    propagate: False

  com.johnmalcolmnorwood.stupidchess:
    level: DEBUG
    handlers: [default]
    propagate: False
