remember_cookie_duration_days: 30
REMEMBER_COOKIE_SECURE: true

app_secret_key: !IncludeText
  filename: !JoinFilePaths
    - !EnvVar SECRETS_VOLUME_PATH
    - flask-app-secret-key

MONGODB_SETTINGS:
  username: stupidchess_mongo_rw
  password: !IncludeText
    filename: !JoinFilePaths
      - !EnvVar SECRETS_VOLUME_PATH
      - mongo-password
